### ISSUE TITLE
Update to Factorio 1.1

### ISSUE THREAD

**Issue by j-rewerts** [DanielSolyom/advanced-equipment#1]
Looks like this mod doesn't work with the new Factorio 1.1 update. Any chance you'd be willing to update?

**Comment by DanielSolyom** [comment]
Hi Jared, currently it's not likely that I will have time to look into this. I am happy to merge pull requests or transfer the ownership of this repository to you.

**Comment by DanielSolyom** [comment]
@j-rewerts the new release 0.0.8 is uploaded to the mod portal, please test it.

**Comment by j-rewerts** [comment]
Closed with #2. Thanks for updating so quickly @DanielSolyom!
